### ISSUE TITLE
Code style for member variables

### ISSUE THREAD

**Issue by seba-eng** [BSI-OFIQ/OFIQ-Project#27]
The code is quite hard to read since member variables are not marked. Therefore it is not easily visible if the variable was defined locally or in the header. Please consider refactoring according to an established C++ style guide like e.g. Google C++ which requires a trailing underscore for members.

**Comment by bbtams** [comment]
Thank you for pointing that out. That would definitely be useful. Although we have a C++style guide we did not put our focus on applying it during finalization and documentation of the first RC. Our team takes care of OFIQ by end of July (as per project plan) and we have other things on the roadmap that have a higher priority. If the ToDo fits in timeline we may fix this by end of July. Otherwise, it will be a topic of a potential follow-up project.
