### ISSUE TITLE
Errors with run_test.cmd

### ISSUE THREAD

**Issue by tadam98** [BSI-OFIQ/OFIQ-Project#3]
After successful completion of 

```
01_conan-install-FaceQAlib.cmd 
02_configure_and_build_FaceQAlib.cmd
03_build_FaceQAlib.cmd
```
The test script `run_ctest.cmd` failed. See attached log.
[run_test.log](https://github.com/BSI-OFIQ/OFIQ-Project/files/12046092/run_test.log)

Also see re-run of the 3 scripts:
[01_conan-install-FaceQAlib.log](https://github.com/BSI-OFIQ/OFIQ-Project/files/12046114/01_conan-install-FaceQAlib.log)
[02_configure_and_build_FaceQAlib.log](https://github.com/BSI-OFIQ/OFIQ-Project/files/12046115/02_configure_and_build_FaceQAlib.log)
[03_build_FaceQAlib.log](https://github.com/BSI-OFIQ/OFIQ-Project/files/12046117/03_build_FaceQAlib.log)

Also: 
`run_sample.cmd`
[ERROR] initialize() returned error: Undefined error.
FaceDetectionError: failed to initialize opencv SDD face detector

I have both Visual Studio 2019 and 2022 installed.
Looks like the `01_conan-install-FaceQAlib.cmd`  identified the VS 2019 See in the log: `compiler.version=16`
And `02_configure_and_build_FaceQAlib.cmd` identified VS2022 (It is not in the log of the rerun, but it identified `compiler.version=17` which is VS2022.

Please make sure that the scripts identify the **same** compiler version. **Preferably VS2022**.

Best,
Mickey Cohen

**Comment by m-schaubert** [comment]
Your installation and build logs don't have any errors, so the build process was successful. In the 02_configure_and_build_FaceQAlib.cmd script, you can see the line `set vs_gen="Visual Studio 16 2019"`, so if you don't pass any arguments to the script, the VS 2019 will be used. And so it was according your [02_configure_and_build_FaceQAlib.log](https://github.com/BSI-OFIQ/OFIQ-Project/files/12046115/02_configure_and_build_FaceQAlib.log): `The CXX compiler identification is MSVC 19.29.30151.0` which is Visual Studio 2019 version 16.

You get the errors because the model files are missing, either you forgot to download them (see the section "Download CNN models" in [GETTINGSTARTED.md](https://github.com/BSI-OFIQ/OFIQ-Project/blob/develop/doc/GETTINGSTARTED.md#download-cnn-models)) or the names of model files are not the same as defined in `.\data\faceqa.jaxn`. Please check that.

**Comment by tadam98** [comment]
You are absolutely right !
I have downloaded and **renamed** adnet and ssd models as documented.
```
run_sample.cmd
Image file: '..\data\images\c-07-twofaces.png' scalar quality: 61.3333
-------------------------------------------------------
ImagFile: '..\data\images\c-07-twofaces.png' has attributes:
TotalFacesPresent-> rawScore:  2   scalar: 0
MouthOpen-> rawScore:  0.00295071   scalar: 96
DynamicRange-> rawScore:  6.95627   scalar: 88
-------------------------------------------------------
```

And also:
```
run_ctest.cmd
Test project C:/Doc/Shanit/2023/Projects/FaceInt/Projects/Code/FaceQ/OFIQ-Project-develop/build/build_win
    Start 1: FaceQAInterface.LoadEmptyConfig
1/7 Test #1: FaceQAInterface.LoadEmptyConfig .....   Passed    0.01 sec
    Start 2: FaceQAInterface.LoadWorkingConfig
2/7 Test #2: FaceQAInterface.LoadWorkingConfig ...   Passed    0.66 sec
    Start 3: Facefinder.FindFace
3/7 Test #3: Facefinder.FindFace .................   Passed    0.27 sec
    Start 4: LandmarkDetector.ADNetLandmarks
4/7 Test #4: LandmarkDetector.ADNetLandmarks .....   Passed    1.08 sec
    Start 5: TotalNumberOfFaces.SSD
5/7 Test #5: TotalNumberOfFaces.SSD ..............   Passed    1.13 sec
    Start 6: DynamicRange.WD5
6/7 Test #6: DynamicRange.WD5 ....................   Passed    1.12 sec
    Start 7: MouthOpen.WD5
7/7 Test #7: MouthOpen.WD5 .......................   Passed    1.11 sec

100% tests passed, 0 tests failed out of 7

Total Test time (real) =   5.40 sec
```
