### ISSUE TITLE
What is the ideal capture distance?

### ISSUE THREAD

**Issue by byteLm** [BSI-OFIQ/OFIQ-Project#52]
We're having problems getting a 100% compliant image, especially when it concerns attributes: HeadSize, UpwardCrop, DownwardCrop and InterEyesDistance.

In real-time captures, we noticed that when approaching the camera the HeadSize.scalarScore and InterEyesDistance.scalarScore attributes approach 100.0, however, the UpwardCrop and DownwardCrop attributes decrease exponentially due to the proximity to the edges of the image, and the same goes for the reverse case. As a result, we can't get a capture in which all these attributes have a .scalarScore greater than 70 at the same time, even after excessive testing.

Is there a reference image that we can follow so that all the attributes have a compliant scalarScore (greater than 70, for example)?

Examples of captures and their respective scores (scalar):
https://ibb.co/k20SDjR
https://ibb.co/GTWwYPL
https://ibb.co/zhN2K4T

**Comment by christophbusch** [comment]
ISO/IEC 29794-5 and the reference implementation OFIQ was developed in order to assess the requirements of ISO/IEC 39794-5 Annex D.1 (which is use case 1) and two other use cases. Following ISO/IEC 29794-1, the quality measures are reported in the range of 0 to 100 with a higher is better understanding.

By no means you should expect a value of 100 for all quality components for a very good image. Also you should NOT anticipate that 70 is a reasonable threshold and you need to exceed that threshold to be compliant.

In the next [meeting](https://sd.iso.org/meetings/136488) of ISO/IEC JTC1 SC37 WG3 we will discuss the variability of quality measure values including hopefully data from operators of the three use cases, which can be the basis for developing best practices (i..e thresholds) for each quality component.

There is a set of conformance test images available at: https://standards.iso.org/iso-iec/29794/-5/ed-1/en/
Further you might want to investigate the images contained in ISO/IEC 39794-5 Annex D.1
